POST  http://localhost:8082/pagamentos-ms/pagamentos
Content-Type: application/json

{
  "valor": 3000.00,
  "nome": "Juca",
  "numero": "0000",
  "expiracao": "10/2028",
  "codigo": 875,
  "status": "CONFIRMADO",
  "formaDePagamentoId": 1,
  "pedidoId": 2
}