POST  http://localhost:8082/pagamentos-ms/pagamentos
Content-Type: application/json

{
  "valor": 400,
  "nome": "Clauionor",
  "numero": "123456",
  "expiracao": "10/2028",
  "codigo": 875,
  "status": "CONFIRMADO",
  "formaDePagamentoId": 1,
  "pedidoId": 2
}