spring:
  datasource:
    url: jdbc:mysql://mysql-pedidos:3306/pedidos_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true