services:

  eureka-server:
    build:
      context: .
      dockerfile: ./eureka-server/Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - pratourbano-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mysql-pagamentos:
    image: mysql:8.0
    container_name: mysql-pagamentos
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pagamento_db
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - pagamentos-db-data:/var/lib/mysql
    networks:
      - pratourbano-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysql-pagamentos", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 50s

  pagamentos-ms:
    build:
      context: .
      dockerfile: ./pagamentos/Dockerfile
    container_name: pagamentos-ms
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-pagamentos:3306/pagamento_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
      - RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=rabbitm
      - SPRING_RABBITMQ_PASSWORD=pratourbano
      - SPRING_APPLICATION_NAME=PAGAMENTOS-MS
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq1:5672,rabbitmq2:5672,rabbitmq3:5672
    networks:
      - pratourbano-network
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql-pagamentos:
        condition: service_healthy
      rabbitmq1:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      retries: 3
      start_period: 50s
      timeout: 5s

  mysql-pedidos:
    image: mysql:8.0
    container_name: mysql-pedidos
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pedidos_db
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - pedidos-db-data:/var/lib/mysql
    networks:
      - pratourbano-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysql-pedidos", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  pedidos-ms:
    build:
      context: .
      dockerfile: ./pedidos/Dockerfile
    container_name: pedidos-ms
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-pedidos:3306/pedidos_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
      - RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=rabbitm
      - SPRING_RABBITMQ_PASSWORD=pratourbano
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq1:5672,rabbitmq2:5672,rabbitmq3:5672
    networks:
      - pratourbano-network
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql-pedidos:
        condition: service_healthy
      rabbitmq1:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 3
      start_period: 40s
      timeout: 5s

  gateway-ms:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    container_name: gateway-ms
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
      - RABBITMQ_HOST=rabbitmq
    networks:
      - pratourbano-network
    depends_on:
      eureka-server:
        condition: service_healthy

  avaliacao-ms:
    build:
      context: .
      dockerfile: ./avaliacao/Dockerfile
    container_name: avaliacao-ms
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=rabbitm
      - SPRING_RABBITMQ_PASSWORD=pratourbano
      - SPRING_APPLICATION_NAME=AVALIACAO-MS
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq1:5672,rabbitmq2:5672,rabbitmq3:5672
    networks:
      - pratourbano-network
    depends_on:
      eureka-server:
        condition: service_healthy
      rabbitmq1:
        condition: service_healthy
      pagamentos-ms:
        condition: service_healthy
      pedidos-ms:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s

  rabbitmq1:
    image: rabbitmq:3.12-management
    hostname: rabbitmq1
    container_name: rabbitmq1
    restart: always
    environment:
      - RABBITMQ_ERLANG_COOKIE=PRATOURBANOCOOKIE
      - RABBITMQ_DEFAULT_USER=rabbitm
      - RABBITMQ_DEFAULT_PASS=pratourbano
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./dados/rabbitmq1:/var/lib/rabbitmq
    networks:
      - pratourbano-network
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  rabbitmq2:
      image: rabbitmq:3.12-management
      hostname: rabbitmq2
      container_name: rabbitmq2
      restart: always
      depends_on:
        - rabbitmq1
      environment:
        - RABBITMQ_ERLANG_COOKIE=PRATOURBANOCOOKIE
        - RABBITMQ_DEFAULT_USER=mqrabbitm
        - RABBITMQ_DEFAULT_PASS=pratourbano
      ports:
        - "5673:5672"
        - "15673:15672"
      volumes:
        - ./dados/rabbitmq2:/var/lib/rabbitmq
      command: >
        bash -c "sleep 10s &&
                rabbitmq-server &
                sleep 30s &&
                rabbitmqctl stop_app &&
                rabbitmqctl join_cluster rabbit@rabbitmq1 &&
                rabbitmqctl start_app &&
                tail -f /dev/null"
      networks:
        - pratourbano-network
      healthcheck:
        test: [ "CMD", "rabbitmqctl", "status" ]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 60s

  rabbitmq3:
      image: rabbitmq:3.12-management
      hostname: rabbitmq3
      container_name: rabbitmq3
      restart: always
      depends_on:
        - rabbitmq1
      environment:
        - RABBITMQ_ERLANG_COOKIE=PRATOURBANOCOOKIE
        - RABBITMQ_DEFAULT_USER=rabbitm
        - RABBITMQ_DEFAULT_PASS=pratourbano
      ports:
        - "5674:5672"
        - "15674:15672"
      volumes:
        - ./dados/rabbitmq3:/var/lib/rabbitmq
      command: >
        bash -c "sleep 20s &&
                rabbitmq-server &
                sleep 30s &&
                rabbitmqctl stop_app &&
                rabbitmqctl join_cluster rabbit@rabbitmq1 &&
                rabbitmqctl start_app &&
                tail -f /dev/null"
      networks:
        - pratourbano-network
      healthcheck:
        test: [ "CMD", "rabbitmqctl", "status" ]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 60s


networks:
  pratourbano-network:
    driver: bridge

volumes:
  pagamentos-db-data:
  pedidos-db-data:
