version: '3.8'  # A versão é obsoleta, você pode removê-la

services:
  eureka:
    build:
      context: eureka  # Atualize se necessário
    ports:
      - "8761:8761"
    networks:
      - pratourbano-network

  mysql-pagamentos:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pagamento_db
    networks:
      - pratourbano-network

  mysql-pedidos:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pedidos_db
    networks:
      - pratourbano-network

  pagamentos-ms:
    image: pratourbano/pagamentos:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-pagamentos:3306/pagamento_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: pagamentos-ms
    deploy:
      replicas: 3
    networks:
      - pratourbano-network

  pedidos-ms:
    image: pratourbano/pedidos:latest
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-pedidos:3306/pedidos_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: pedidos-ms
    deploy:
      replicas: 3
    networks:
      - pratourbano-network

  gateway-ms:
    image: pratourbano/gateway:latest
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: gateway-ms
    networks:
      - pratourbano-network

networks:
  pratourbano-network:
    driver: overlay  # Certifique-se de usar o driver overlay