spring:
  application:
    name: pagamentos-ms

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true