spring:
  application:
    name: AVALIACAO-MS
  rabbitmq:
    addresses: rabbitmq1:5672,rabbitmq2:5672,rabbitmq3:5672
    username: rabbitm
    password: pratourbano
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2.0
    connection-timeout: 5000
    publisher-confirm-type: correlated
    publisher-returns: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.value}

server:
  port: 8083