
POST http://localhost:8082/pedidos
Content-Type: application/json

{
  "itens": [
    {
        "quantidade": 10,
        "descrição": "Coca-cola"
    },
    {
        "quantidade": 5,
        "descrição": "Mc Chicken"
    }
    ]

}