
POST http://localhost:8081/pedidos
Content-Type: application/json

{
  "itens": [
    {
        "quantidade": 10,
        "descrição": "Coca-cola",
        "status": "CONFIRMADO"
    },
    {
        "quantidade": 5,
        "descrição": "Mc Chicken",
         "status": "ENTREGUE"
    }
    ]

}