server:
  port: 8082

spring:
  main:
    web-application-type: reactive
  application:
    name: GATEWAY-MS
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: pedidos-service
          uri: lb://PEDIDOS-MS
          predicates:
            - Path=/pedidos/**
          filters:
            - RewritePath=/pedidos/(?<segment>.*), /${segment}

        - id: pagamentos-service
          uri: lb://PAGAMENTOS-MS
          predicates:
            - Path=/pagamentos/**
          filters:
            - RewritePath=/pagamentos/(?<segment>.*), /${segment}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/ # O URL do Eureka Server
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG

