spring:
  application:
    name: PAGAMENTOS-MS
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  rabbitmq:
    addresses: rabbitmq1:5672,rabbitmq2:5672,rabbitmq3:5672
    username: rabbitm
    password: pratourbano
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2.0
    connection-timeout: 5000
    publisher-confirm-type: correlated
    publisher-returns: true

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${random.uuid}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      atualizaPedido:
        sliding-window-size: 3 #quantas requisicoes/estatisticas serão feitas para o circuit breaker(aberto/fechado)
        minimum-number-of-calls: 2 #minimo chamadas até entrar em ação
        wait-duration-in-open-state: 50s #quanto tempo mantem estado aberto