

spring:
  datasource:
    url: jdbc:mysql://mysql-pagamentos:3306/pagamento_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
    hostname: pagamentos-ms

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always




# application-docker.yml
# spring:
#   datasource:
#     url: jdbc:mysql://mysql-pagamentos:3306/pagamento_db
#     username: root
#     password: root
#   jpa:
#     hibernate:
#       ddl-auto: none
#     show-sql: true
#   flyway:
#     enabled: true
#     locations: classpath:db/migration
#
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://host.docker.internal:8761/eureka
#   instance:
#     prefer-ip-address: true
#     hostname: ${spring.application.name}
#
# management:
#   endpoints:
#     web:
#       exposure:
#         include: health,info
#   health:
#     show-details: always