server:
  port: 8761

spring:
  application:
    name: EUREKA-SERVER
  cloud:
    config:
      enabled: false

eureka:
  client:
    registerWithEureka: false   # Desabilita o registro no próprio Eureka
    fetchRegistry: false        # O Eureka não busca a lista dos serviços (não sincroniza consigo mesmo)
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.value}
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enable-self-preservation: false